/** =========================================================================
 *
 *  Supacharger - Plugin Registry
 *
 *  Description: This file is auto generated by npm run build. Do not edit.
 *
 * ========================================================================= */