import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import Link from 'next/link';
import { IoLogoFacebook, IoLogoInstagram, IoLogoTwitter } from 'react-icons/io5';
import { cookies } from 'next/headers';
import { Logo } from '@/components/logo';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/utils/cn';
import { Analytics } from '@vercel/analytics/react';
import { NextIntlClientProvider } from 'next-intl';


import { Navigation } from './navigation';

import '@/styles/globals.css';

export const dynamic = 'force-dynamic';

const figtree = Figtree({
  variable: '--font-figtree',
  subsets: ['latin'],
});

const site_title = process.env.SITE_TITLE;

export const metadata: Metadata = {
  title: site_title,
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: PropsWithChildren) {
   // Get the current locale from cookies
   const cookieStore = await cookies();
   const currentLocale = cookieStore.get('supacharger_locale')?.value || 'en'; // Default to 'en' if not set
   // Load translations for the current locale
   const messages = await import(`../../messages/${currentLocale}.json`).then((module) => module.default);

   return (
      <html lang={currentLocale}>
         <body className={cn('font-sans antialiased', figtree.variable)}>
            <NextIntlClientProvider messages={messages}>
               <div className="m-auto flex h-full flex-col">
                  <AppBar />
                  <main className="relative flex-1">
                     <div className="relative h-full">{children}</div>
                  </main>
                  <Footer />
               </div>
               <Toaster />
               <Analytics />
            </NextIntlClientProvider>
         </body>
      </html>
   );
}

async function AppBar() {
   return (
      <header className="flex items-center justify-between py-8  px-4">
         <Logo />
         <Navigation />
      </header>
   );
}

function Footer() {
   return (
      <footer className="mt-8 flex flex-col gap-8 text-neutral-400 lg:mt-32">
         <div className="flex flex-col justify-between gap-8 lg:flex-row">
            <div>
               <Logo />
            </div>
            <div className="grid grid-cols-2 gap-8 sm:grid-cols-4 lg:grid-cols-4 lg:gap-16">
               <div className="flex flex-col gap-2 lg:gap-6">
                  <div className="font-semibold text-neutral-100">Product</div>
                  <nav className="flex flex-col gap-2 lg:gap-6">
                     <Link href="/pricing">Pricing</Link>
                  </nav>
               </div>
               <div className="flex flex-col gap-2 lg:gap-6">
                  <div className="font-semibold text-neutral-100">Company</div>
                  <nav className="flex flex-col gap-2 lg:gap-6">
                     <Link href="/about-us">About Us</Link>
                     <Link href="/privacy">Privacy</Link>
                  </nav>
               </div>
               <div className="flex flex-col gap-2 lg:gap-6">
                  <div className="font-semibold text-neutral-100">Support</div>
                  <nav className="flex flex-col gap-2 lg:gap-6">
                     <Link href="/support">Get Support</Link>
                  </nav>
               </div>
               <div className="flex flex-col gap-2 lg:gap-6">
                  <div className="font-semibold text-neutral-100">Follow us</div>
                  <nav className="flex flex-col gap-2 lg:gap-6">
                     <Link href="#">
                        <span className="flex items-center gap-2">
                           <IoLogoTwitter size={22} /> 
                           <span>Twitter</span>
                        </span>
                     </Link>
                     <Link href="#">
                        <span className="flex items-center gap-2">
                           <IoLogoFacebook size={22} /> 
                           <span>Facebook</span>
                        </span>
                     </Link>
                     <Link href="#">
                        <span className="flex items-center gap-2">
                           <IoLogoInstagram size={22} /> 
                           <span>Instagram</span>
                        </span>
                     </Link>
                  </nav>
               </div>
            </div>
         </div>
         <div className="border-t border-zinc-800 py-6 text-center">
            <span className="text-neutral4 text-xs">
               Copyright {new Date().getFullYear()} &copy; {site_title}
            </span>
         </div>
      </footer>
   );
}
